### ISSUE TITLE
Uncaught SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by JohnMcLear** [dcdc-io/node-gp-phonegap#2]
https://github.com/dcdc-io/node-gp-phonegap/blob/master/www/js/index.js#L39

HTC One M8.

Just quickly posting this before jumping on a plane

```
try {
  var k = new Map();
  console.log("ES6 supported!!")
} catch(err) {
  console.log("ES6 not supported :(")
}

try {
  var k = new HashMap();
  console.log("ES100 supported!!")
} catch(err) {
  console.log("ES100 not supported :(")
}
VM68:3 ES6 supported!!
VM68:12 ES100 not supported :(
undefined
```

**Comment by benbenbenbenbenben** [comment]
Looks like your HTC One M8 is using a WebView that doesn't support async/await.

I've added webpack and babel to transpile down.

edit: work in `src/index.js` now instead of `www/js/index.js`

--

Fixed in https://github.com/dcdc-io/node-gp-phonegap/commit/22d335ebbb8868a00a73f4b3685c727618ad63dc
